### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by jarednorman** [zenhob/hcl#74]
All the commands I've tried seem to hang for me for a few minutes sometimes (but they eventually complete.) Sometimes they work as expected (almost immediately.) I've seen no errors reported on the Harvest status page.

When I `^C` out while it's hanging I get the following:

```
/home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Interrupt
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /home/jared/.rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/request/authorization.rb:38:in `call'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/harvest_middleware.rb:19:in `call'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
        from /home/jared/.gem/ruby/2.2.3/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/net.rb:31:in `get'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/timesheet_resource.rb:44:in `block in resources'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/day_entry.rb:40:in `with_timer'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/commands.rb:138:in `note'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/app.rb:49:in `run'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/lib/hcl/app.rb:28:in `command'
        from /home/jared/.gem/ruby/2.2.3/gems/hcl-0.4.15/bin/hcl:4:in `<top (required)>'
        from /home/jared/.gem/ruby/2.2.3/bin/hcl:23:in `load'
        from /home/jared/.gem/ruby/2.2.3/bin/hcl:23:in `<main>'
```

I've confirmed this issue on multiple machines and networks, but my coworkers don't seem to be having any issues. Any ideas?

**Comment by jarednorman** [comment]
Haven't experienced the issue this week yet, suspecting it was on their side, but still a little confused. I'll call this closed.
