### ISSUE TITLE
`hcl status` command throws an error

### ISSUE THREAD

**Issue by mclark-newvistas** [zenhob/hcl#93]
What happened:
```
$ hcl status
Traceback (most recent call last):
    5: from /home/michael/.gem/ruby/2.5.0/bin/hcl:23:in `<main>'
    4: from /home/michael/.gem/ruby/2.5.0/bin/hcl:23:in `load'
    3: from /home/michael/.gem/ruby/2.5.0/gems/hcl-0.4.17/bin/hcl:4:in `<top (required)>'
    2: from /home/michael/.gem/ruby/2.5.0/gems/hcl-0.4.17/lib/hcl/app.rb:28:in `command'
    1: from /home/michael/.gem/ruby/2.5.0/gems/hcl-0.4.17/lib/hcl/app.rb:49:in `run'
/home/michael/.gem/ruby/2.5.0/gems/hcl-0.4.17/lib/hcl/commands.rb:20:in `status': undefined method `[]' for nil:NilClass (NoMethodError)
```

What I expected: show API status as normal

System information:

```
$ hcl --version
HCl version 0.4.17
$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
$ lsb_release -ir
Distributor ID: Arch
Release:    rolling
$ checkupdates # system is up to date
$ gem update
Updating installed gems
Nothing to update
```

**Comment by pejer** [comment]
https://github.com/zenhob/hcl/pull/96

Would fix that issue.

**Comment by zenhob** [comment]
thanks for the patch, this will be fixed in the next release
